/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exam_portal;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author abhis
 */
public class controlHomeNonTech extends javax.swing.JFrame {

    /**
     * Creates new form controlHomeNonTech
     */
    public controlHomeNonTech() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jTextField3 = new javax.swing.JTextField();
        jTextField38 = new javax.swing.JTextField();
        panel3 = new java.awt.Panel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        panel2 = new java.awt.Panel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        panel5 = new java.awt.Panel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jTextField25 = new javax.swing.JTextField();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jTextField30 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jTextField39 = new javax.swing.JTextField();
        jTextField40 = new javax.swing.JTextField();
        jTextField41 = new javax.swing.JTextField();
        jTextField42 = new javax.swing.JTextField();
        jTextField43 = new javax.swing.JTextField();
        jTextField44 = new javax.swing.JTextField();
        jTextField45 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTextField9 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel1.setBackground(new java.awt.Color(0, 0, 0));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Harlow Solid Italic", 3, 24)); // NOI18N
        jTextField3.setText("A.S.K School Of Higher Studies");
        jTextField3.setPreferredSize(new java.awt.Dimension(365, 39));
        panel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jTextField38.setEditable(false);
        jTextField38.setText("NOTE->Do Not Schedule Two Exams On Same Day(see confirm toi see block after confirm)");
        panel1.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 520, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 83));

        panel3.setBackground(new java.awt.Color(51, 51, 255));
        panel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(51, 255, 51));
        jButton1.setText("Schedule Exam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jButton2.setText("See Datesheet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/education back.jpg"))); // NOI18N
        panel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, 140));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-cancel-24.png"))); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        getContentPane().add(panel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 146, 440));

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jTextField4.setText("Make Exam Schedule");
        getContentPane().add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, -1, -1));

        jButton3.setText("Technical Courses");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jButton4.setBackground(new java.awt.Color(51, 255, 51));
        jButton4.setText("Non Technical Courses");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        panel2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(0, 0, 0));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("email : askschoolofhigherstudies@org.in");
        panel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-square-play-button-for-android-application-store-24.png"))); // NOI18N
        panel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 56, 39));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-instagram-48.png"))); // NOI18N
        panel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, 40));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Contact : +91-123456789");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        panel2.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 150, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-twitter-48.png"))); // NOI18N
        panel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 50, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-facebook-30.png"))); // NOI18N
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 40, 20));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 730, -1));

        panel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField5.setEditable(false);
        jTextField5.setText("Human Resource");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 28, 132, -1));

        jTextField6.setEditable(false);
        jTextField6.setText("A.Human Resource");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        panel5.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 186, 132, -1));

        jTextField7.setEditable(false);
        jTextField7.setText("Subject");
        panel5.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 0, 71, -1));

        jTextField8.setEditable(false);
        jTextField8.setText(" Date(dd/mm/yyyy)");
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        panel5.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 120, -1));

        jTextField10.setEditable(false);
        jTextField10.setText("Account");
        panel5.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 56, 132, -1));

        jTextField11.setEditable(false);
        jTextField11.setText("Economics");
        panel5.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 84, 132, -1));

        jTextField12.setEditable(false);
        jTextField12.setText("Bussiness");
        panel5.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 118, 132, -1));

        jTextField13.setEditable(false);
        jTextField13.setText("Soft Skills");
        panel5.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 152, 132, -1));

        jTextField14.setEditable(false);
        jTextField14.setText("A.Account");
        panel5.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 132, -1));

        jTextField15.setEditable(false);
        jTextField15.setText("A.Economics");
        panel5.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 254, 132, -1));

        jTextField16.setEditable(false);
        jTextField16.setText("A.Bussiness");
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        panel5.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 288, 132, -1));

        jTextField17.setEditable(false);
        jTextField17.setText("A.OS");
        panel5.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 322, 132, -1));

        jTextField18.setEditable(false);
        panel5.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 320, 141, -1));
        panel5.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 56, 140, -1));
        panel5.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 84, 140, -1));
        panel5.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 118, 140, -1));
        panel5.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 186, 140, -1));
        panel5.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 152, 140, -1));
        panel5.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 220, 140, -1));
        panel5.add(jTextField25, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 254, 140, -1));
        panel5.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 288, 140, -1));
        panel5.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 322, 140, -1));

        jTextField28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField28ActionPerformed(evt);
            }
        });
        panel5.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 28, 141, -1));

        jTextField29.setEditable(false);
        jTextField29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField29ActionPerformed(evt);
            }
        });
        panel5.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, 141, -1));

        jTextField30.setEditable(false);
        panel5.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 141, -1));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setText("Confirm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, -1, -1));

        jTextField39.setEditable(false);
        panel5.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 90, 141, -1));

        jTextField40.setEditable(false);
        panel5.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 141, -1));

        jTextField41.setEditable(false);
        panel5.add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 141, -1));

        jTextField42.setEditable(false);
        panel5.add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 141, -1));

        jTextField43.setEditable(false);
        panel5.add(jTextField43, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 141, -1));

        jTextField44.setEditable(false);
        panel5.add(jTextField44, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 141, -1));

        jTextField45.setEditable(false);
        panel5.add(jTextField45, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 141, -1));

        jButton6.setBackground(new java.awt.Color(255, 51, 51));
        jButton6.setText("Submit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panel5.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        jTextField9.setEditable(false);
        jTextField9.setText("Confirm to see ");
        panel5.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, -1, -1));

        getContentPane().add(panel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 153, 570, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new controlHome().setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Do not Skip Any exam Date and do not schedule Two exams on same day");
        String physics=jTextField28.getText();
        String maths=jTextField19.getText();
        String em=jTextField20.getText();
        String dbms=jTextField21.getText();
        String os=jTextField23.getText();
        
        String aphysics=jTextField22.getText();
        String amaths=jTextField24.getText();
        String aem=jTextField25.getText();
        String adbms=jTextField26.getText();
        String aos=jTextField27.getText();
        
        jTextField29.setText(physics);
        jTextField30.setText(maths);
        jTextField39.setText(em);
        jTextField40.setText(dbms);
        jTextField41.setText(os);
        jTextField42.setText(aphysics);
        jTextField43.setText(amaths);
        jTextField44.setText(aem);
        jTextField45.setText(adbms);
        jTextField18.setText(aos);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField29ActionPerformed

    private void jTextField28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField28ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         String physics=jTextField28.getText();
        String maths=jTextField19.getText();
        String em=jTextField20.getText();
        String dbms=jTextField21.getText();
        String os=jTextField23.getText();
        
        String aphysics=jTextField22.getText();
        String amaths=jTextField24.getText();
        String aem=jTextField25.getText();
        String adbms=jTextField26.getText();
        String aos=jTextField27.getText();
        if(physics.length()>0 && maths.length()>0 && em.length()>0 && dbms.length()>0 && os.length()>0 && aphysics.length()>0 && amaths.length()>0 && aos.length()>0 && aem.length()>0 && dbms.length()>0 ){
            try{
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/srm","root","Abhik@123#");
                Statement st=con.createStatement();
               
                
                st.executeUpdate("update nontech set date='"+physics+"' where subject='humanresource'"); 
                  st.executeUpdate("update nontech set date=  '"+maths+"' where subject='account'");
                 st.executeUpdate("update nontech set date= '"+em+"' where subject='economics'");
                 st.executeUpdate("update nontech set date=  '"+dbms+"' where subject='bussiness'");
                 st.executeUpdate("update nontech set date= '"+os+"' where subject='softskill'");
                 
                 st.executeUpdate("update nontech set  date=  '"+aphysics+"' where subject='advance_humanresource'");
                 st.executeUpdate("update nontech set  date=  '"+amaths+"' where subject='advance_account'");
                 st.executeUpdate("update nontech set   date= '"+aem+"' where subject='advance_economics'");
                 st.executeUpdate("update nontech set  date=  '"+adbms+"' where subject='advance_bussiness'");
                 st.executeUpdate("update nontech set  date=  '"+aos+"' where subject='advance_softskill'");
                 
                    JOptionPane.showMessageDialog(null, "Updated");
                
            
        }
        catch(Exception e){
             JOptionPane.showMessageDialog(null, e.toString());
        }
        }
        else{
            JOptionPane.showMessageDialog(null, "any one or more of the field is empty");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new datesheetController().setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new examControllerHome().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(controlHomeNonTech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(controlHomeNonTech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(controlHomeNonTech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(controlHomeNonTech.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new controlHomeNonTech().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField25;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField43;
    private javax.swing.JTextField jTextField44;
    private javax.swing.JTextField jTextField45;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel5;
    // End of variables declaration//GEN-END:variables
}
