/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exam_portal;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Paper;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author abhis
 */
public class studentResult extends javax.swing.JFrame {

    /**
     * Creates new form studentResult
     */
    public studentResult() {
        initComponents();
    }
    public studentResult(String rollno,String course) {
        initComponents();
         jTextField3.setText(rollno);
         jTextField1.setText(course);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        panel1.setPreferredSize(new java.awt.Dimension(595, 842));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Roll no. :");
        panel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 87, -1));

        jTextField3.setEditable(false);
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        panel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 225, -1));

        jLabel2.setText("Name :");
        panel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 87, -1));

        jTextField2.setEditable(false);
        panel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 225, -1));

        jLabel1.setText("Course Name :");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 87, -1));

        jTextField1.setEditable(false);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        panel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 225, -1));

        jLabel4.setText("Branch :");
        panel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 60, -1));

        jTextField5.setEditable(false);
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 225, -1));

        jLabel5.setText("Gender :");
        panel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(387, 100, 80, -1));

        jTextField4.setEditable(false);
        panel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 225, -1));

        jLabel6.setText("Father Name :");
        panel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 87, -1));

        jTextField6.setEditable(false);
        panel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 225, -1));

        jLabel7.setText("Total Marks");
        panel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 72, -1));

        jLabel13.setText("100");
        panel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 72, -1));

        jLabel14.setText("100");
        panel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 72, -1));

        jLabel15.setText("100");
        panel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 72, -1));

        jLabel18.setText("100");
        panel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 72, -1));

        jLabel16.setText("100");
        panel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 390, 72, -1));

        jLabel17.setText("Passing Marks");
        panel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, 84, -1));

        jLabel19.setText("30");
        panel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 72, -1));

        jLabel20.setText("30");
        panel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 72, -1));

        jLabel21.setText("30");
        panel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 300, 72, -1));

        jLabel22.setText("30");
        panel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, 72, -1));

        jLabel23.setText("30");
        panel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 390, 72, -1));

        jLabel8.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel8.setText("Physics");
        panel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, -1));

        jLabel9.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel9.setText("Maths");
        jLabel9.setPreferredSize(new java.awt.Dimension(37, 16));
        panel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 130, -1));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel10.setText("EM");
        jLabel10.setPreferredSize(new java.awt.Dimension(37, 16));
        panel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 130, -1));

        jLabel11.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel11.setText("DBMS");
        jLabel11.setPreferredSize(new java.awt.Dimension(37, 16));
        panel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 130, 20));

        jLabel12.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        jLabel12.setText("OS");
        jLabel12.setPreferredSize(new java.awt.Dimension(37, 16));
        panel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 130, -1));

        jLabel24.setText("Marks Obtained");
        panel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jTextField7.setEditable(false);
        panel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 210, 77, -1));

        jTextField9.setEditable(false);
        panel1.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 77, -1));

        jTextField8.setEditable(false);
        panel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 77, -1));

        jTextField10.setEditable(false);
        panel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 340, 77, -1));

        jTextField11.setEditable(false);
        panel1.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 77, -1));

        jLabel30.setText("Total Marks");
        panel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 72, -1));

        jTextField13.setEditable(false);
        panel1.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 77, -1));

        jTextField12.setEditable(false);
        panel1.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 470, 77, -1));

        jTextField14.setEditable(false);
        jTextField14.setText("Status");
        panel1.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 470, 77, -1));

        jTextField15.setEditable(false);
        jTextField15.setText("Electronically Signed");
        panel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 520, -1, -1));

        jTextField16.setEditable(false);
        jTextField16.setBackground(new java.awt.Color(51, 255, 255));
        jTextField16.setFont(new java.awt.Font("Segoe UI", 3, 32)); // NOI18N
        jTextField16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField16.setText("MARKSHEET");
        jTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField16ActionPerformed(evt);
            }
        });
        panel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 470, 40));

        jLabel25.setBackground(new java.awt.Color(0, 255, 204));
        jLabel25.setForeground(new java.awt.Color(255, 255, 204));
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/marksheet.jpg"))); // NOI18N
        panel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 690, 520));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/Dark-Blue-Background-main.jpg"))); // NOI18N
        panel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 580));

        jButton2.setText("Print");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        String course=jTextField1.getText();
        switch (course) {
            case "BTech" -> {
                 try{
                     jLabel8.setText("Physics");
                     jLabel9.setText("Maths");
                     jLabel10.setText("EM");
                     jLabel11.setText("DBMS");
                     jLabel12.setText("OS");
                     
            String rollno=jTextField3.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/srm","root","Abhik@123#");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from student inner join result where student.rollno='"+rollno+"' and result.rollno='"+rollno+"'");
            if(rs.next()){
                jTextField1.setText(rs.getString(2));// after joining course is at 2 column
                jTextField2.setText(rs.getString(4));// name
                 jTextField5.setText(rs.getString(3));// branch
                  jTextField4.setText(rs.getString(5));//gender
                   jTextField6.setText(rs.getString(6));//fathername
                   
                jTextField7.setText(rs.getString(8));// physics
                jTextField9.setText(rs.getString(9));// maths
                 jTextField8.setText(rs.getString(10));// em
                  jTextField10.setText(rs.getString(11));//dbms
                   jTextField11.setText(rs.getString(12));//os
                    
                        //calculation of total marks
                    int p=Integer.parseInt(jTextField7.getText());
                    int m=Integer.parseInt(jTextField9.getText());
                    int e=Integer.parseInt(jTextField8.getText());
                    int d=Integer.parseInt(jTextField10.getText());
                    int o=Integer.parseInt(jTextField11.getText());
                   int sum=p+m+e+d+o;
                    jTextField13.setText(String.valueOf(sum))  ;      //total marks
                    int avg=sum/5;
                    
                    if(avg>32){
                        jTextField12.setText("Passed");          //status
                    }else{
                jTextField12.setText("Failed");          //status
            }
                    
                   
                   
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"e.toString()");
            
        }
            }
            case "MTech" -> {
                 try{
                      jLabel8.setText("Adv Physics");
                     jLabel9.setText("Adv Maths");
                     jLabel10.setText("Adv EM");
                     jLabel11.setText("Adv DBMS");
                     jLabel12.setText("Adv OS");
            String rollno=jTextField3.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/srm","root","Abhik@123#");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from student inner join resultmt where student.rollno='"+rollno+"' and resultmt.rollno='"+rollno+"'");
            if(rs.next()){
                jTextField1.setText(rs.getString(2));// after joining course is at 2 column
                jTextField2.setText(rs.getString(4));// name
                 jTextField5.setText(rs.getString(3));// branch
                  jTextField4.setText(rs.getString(5));//gender
                   jTextField6.setText(rs.getString(6));//fathername
                   
                jTextField7.setText(rs.getString(8));// physics
                jTextField9.setText(rs.getString(9));// maths
                 jTextField8.setText(rs.getString(10));// em
                  jTextField10.setText(rs.getString(11));//dbms
                   jTextField11.setText(rs.getString(12));//os
                    
                        //calculation of total marks
                    int p=Integer.parseInt(jTextField7.getText());
                    int m=Integer.parseInt(jTextField9.getText());
                    int e=Integer.parseInt(jTextField8.getText());
                    int d=Integer.parseInt(jTextField10.getText());
                    int o=Integer.parseInt(jTextField11.getText());
                   int sum=p+m+e+d+o;
                    jTextField13.setText(String.valueOf(sum))  ;      //total marks
                    int avg=sum/5;
                    
                    if(avg>32){
                        jTextField12.setText("Passed");          //status
                    }else{
                jTextField12.setText("Failed");          //status
            }
                    
                   
                   
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"e.toString()");
            
        }
            }
            case "MBA" -> {
                 try{
                     jLabel8.setText("Adv HR");
                     jLabel9.setText("Adv Account");
                     jLabel10.setText("Adv Economics");
                     jLabel11.setText("Adv Bussiness");
                     jLabel12.setText("Adv Soft Skills");
            String rollno=jTextField3.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/srm","root","Abhik@123#");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from student inner join resultmb where student.rollno='"+rollno+"' and resultmb.rollno='"+rollno+"'");
            if(rs.next()){
                jTextField1.setText(rs.getString(2));// after joining course is at 2 column
                jTextField2.setText(rs.getString(4));// name
                 jTextField5.setText(rs.getString(3));// branch
                  jTextField4.setText(rs.getString(5));//gender
                   jTextField6.setText(rs.getString(6));//fathername
                   
                jTextField7.setText(rs.getString(8));// physics
                jTextField9.setText(rs.getString(9));// maths
                 jTextField8.setText(rs.getString(10));// em
                  jTextField10.setText(rs.getString(11));//dbms
                   jTextField11.setText(rs.getString(12));//os
                    
                        //calculation of total marks
                    int p=Integer.parseInt(jTextField7.getText());
                    int m=Integer.parseInt(jTextField9.getText());
                    int e=Integer.parseInt(jTextField8.getText());
                    int d=Integer.parseInt(jTextField10.getText());
                    int o=Integer.parseInt(jTextField11.getText());
                   int sum=p+m+e+d+o;
                    jTextField13.setText(String.valueOf(sum))  ;      //total marks
                    int avg=sum/5;
                    
                    if(avg>32){
                        jTextField12.setText("Passed");          //status
                    }else{
                jTextField12.setText("Failed");          //status
            }
                    
                   
                   
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"e.toString()");
            
        }
            }
            default -> {
                 try{
                     jLabel8.setText("HR");
                     jLabel9.setText("Account");
                     jLabel10.setText("Economics");
                     jLabel11.setText("Bussiness");
                     jLabel12.setText("Soft Skills");
            String rollno=jTextField3.getText();
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/srm","root","Abhik@123#");
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery("select * from student inner join resultbb where student.rollno='"+rollno+"' and resultbb.rollno='"+rollno+"'");
            if(rs.next()){
                jTextField1.setText(rs.getString(2));// after joining course is at 2 column
                jTextField2.setText(rs.getString(4));// name
                 jTextField5.setText(rs.getString(3));// branch
                  jTextField4.setText(rs.getString(5));//gender
                   jTextField6.setText(rs.getString(6));//fathername
                   
                jTextField7.setText(rs.getString(8));// physics
                jTextField9.setText(rs.getString(9));// maths
                 jTextField8.setText(rs.getString(10));// em
                  jTextField10.setText(rs.getString(11));//dbms
                   jTextField11.setText(rs.getString(12));//os
                    
                        //calculation of total marks
                    int p=Integer.parseInt(jTextField7.getText());
                    int m=Integer.parseInt(jTextField9.getText());
                    int e=Integer.parseInt(jTextField8.getText());
                    int d=Integer.parseInt(jTextField10.getText());
                    int o=Integer.parseInt(jTextField11.getText());
                   int sum=p+m+e+d+o;
                    jTextField13.setText(String.valueOf(sum))  ;      //total marks
                    int avg=sum/5;
                    
                    if(avg>32){
                        jTextField12.setText("Passed");          //status
                    }else{
                jTextField12.setText("Failed");          //status
            }
                    
                   
                   
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"e.toString()");
            
        }
            }
        }
    }//GEN-LAST:event_formComponentShown

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new studentHome().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
//        Graphics g = panel1.getGraphics();
//        panel1.print(g);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        jButton2.setVisible(false);
        PrinterJob job = PrinterJob.getPrinterJob();
//        PageFormat format = job.defaultPage();
//        Paper paper = format.getPaper();
//        paper.setSize(595, 842); // A4 size in points (72 points per inch)
//        paper.setImageableArea(36, 36, 523, 770); // Margin of 1 inch (72 points) on each side
//        format.setPaper(paper);
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                  // Create a PrinterJob and set the page size to A4
        PrinterJob job = PrinterJob.getPrinterJob();
        PageFormat format = job.defaultPage();
        
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel1.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
         jButton2.setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentResult.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentResult().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private java.awt.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
