/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package exam_portal;

import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author abhis
 */
public class studentHome extends javax.swing.JFrame {

    /**
     * Creates new form studentHome
     */
    public studentHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        panel1 = new java.awt.Panel();
        jTextField3 = new javax.swing.JTextField();
        panel2 = new java.awt.Panel();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Course");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 80, -1));

        jButton3.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-search-30.png"))); // NOI18N
        jButton3.setText("Search");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setPreferredSize(new java.awt.Dimension(99, 37));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 296, -1, -1));

        jButton4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-cancel-24.png"))); // NOI18N
        jButton4.setText("Back");
        jButton4.setPreferredSize(new java.awt.Dimension(99, 37));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 296, -1, -1));
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 250, 247, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Result Portal");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 247, 57));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Roll Number");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 250, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MTech", "BTech", "MBA", "BBA" }));
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 250, -1));

        panel1.setBackground(new java.awt.Color(0, 0, 0));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Harlow Solid Italic", 3, 24)); // NOI18N
        jTextField3.setText("A.S.K School Of Higher Studies");
        jTextField3.setPreferredSize(new java.awt.Dimension(365, 39));
        panel1.add(jTextField3);

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, -1));

        panel2.setBackground(new java.awt.Color(0, 0, 0));
        panel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(0, 0, 0));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("email : askschoolofhigherstudies@org.in");
        panel2.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(0, 0, 0));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("Contact : +91-123456789");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        panel2.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 150, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-square-play-button-for-android-application-store-24.png"))); // NOI18N
        panel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 0, 30, 39));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-instagram-48.png"))); // NOI18N
        panel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, -1, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-facebook-30.png"))); // NOI18N
        panel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, -1, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-twitter-48.png"))); // NOI18N
        panel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, -1, 40));

        getContentPane().add(panel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 680, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-facebook-30.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, -1, 20));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/icons8-twitter-48.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, 40));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/Tech Back.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 680, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/exam_portal/Tech Back.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 680, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String rollno=jTextField2.getText();
         String course;
        course = (String) jComboBox1.getSelectedItem();
        switch (course) {
            case "BTech" -> {
                try{
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/srm","root","Abhik@123#");
                    Statement st=con.createStatement();
                    ResultSet rsbt=st.executeQuery("select * from student inner join result where student.course='"+course+"' and result.rollno='"+rollno+"'"); // join table and search if roll no present in both table or not;
                    if(rsbt.next()){
                        setVisible(false);
                        new studentResult(rollno,course).setVisible(true);
                        
                    }
                    else{
                        JOptionPane.showMessageDialog(null,"Incorrect roll number");
                    }
                    
                }
                
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"e.toString()");
                }
            }
            case "MTech" -> {
                try{
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/srm","root","Abhik@123#");
                    Statement st=con.createStatement();  
          ResultSet rsmt=st.executeQuery("select * from student inner join resultmt where student.rollno='"+rollno+"' and resultmt.rollno='"+rollno+"'");
                if(rsmt.next()){
                setVisible(false);
                new studentResult(rollno,course).setVisible(true);

            }
                else{
                    JOptionPane.showMessageDialog(null,"Incorrect roll number");
                }

                }
                
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"e.toString()");
                }
            }
            case "MBA" -> {
                try{
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/srm","root","Abhik@123#");
                    Statement st=con.createStatement();
                   ResultSet rsmb=st.executeQuery("select * from student inner join resultmb where student.rollno='"+rollno+"' and resultmb.rollno='"+rollno+"'");
                if(rsmb.next()){
                    setVisible(false);
                    new studentResult(rollno,course).setVisible(true);

                }
            else{
                JOptionPane.showMessageDialog(null,"Incorrect roll number");
            }

                }
                
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"e.toString()");
                }
            }
            default -> {
                try{
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/srm","root","Abhik@123#");
                    Statement st=con.createStatement();
                    ResultSet rsbt=st.executeQuery("select * from student inner join result where student.course='"+course+"' and result.rollno='"+rollno+"'"); // join table and search if roll no present in both table or not;
                   ResultSet rsbb=st.executeQuery("select * from student inner join resultbb where student.rollno='"+rollno+"' and resultbb.rollno='"+rollno+"'");

                if(rsbb.next()){
                    setVisible(false);
                    new studentResult(rollno,course).setVisible(true);

                }
                else{
                    JOptionPane.showMessageDialog(null,"Incorrect roll number");
                }

                }
                
                catch(Exception e){
                    JOptionPane.showMessageDialog(null,"e.toString()");
                }
            }
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new adminIndex().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    // End of variables declaration//GEN-END:variables
}
